apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: tanishab3/event-backend
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: mongodb+srv://tanu:hYitUCaQy3S84rr7@cluster0.vvz9jv5.mongodb.net/?appName=Cluster0